spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.jsp
server.port = 6161
# PostgreSQL example
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_one
spring.datasource.username=postgres
spring.datasource.password=Nashik@04
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true